# Data Preprocessing Tools

## Importing the libraries

In [0]:
#numpy: for arrays
#matplotlib: plots
#pandas: import data sets and create matrix of features (ie. variables);preprocess and import data sets

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
#create a new variable that contains the data set with its data frames
#dataset has FEATURES and DEPENDENT VARIABLES
#Features: data that predicts dep. variables
#iloc():locate index (of columns and/or rows)

In [0]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values #get first three col. and all rows
y = dataset.iloc[:, -1].values #get last column and all rows

In [18]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [19]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [0]:
#replace missing data by average of all the values in that data element
#scikit learn: data science library
#Class: simpleimputer ---> object will allow us to replace blanks in data

#fit(): connects imputer to matrix of features;accepts columns w/ numerical values
#transform():replaces blank w/ the avg.

In [0]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [21]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding ccatategorical data

In [0]:
# Encode alphabetical, non-numeric values into numeric values
# Encode these values with binary numbers
# X needs to be transformed into an array of features

### Encoding the Independent Variable

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [23]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [0]:
# Train set: train ML models on existing data/observations
# Test set: Evaluate model performance on new observations
# Training observation = 80%, Test observation = 20%

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1)

In [27]:
print(x_train)

[[0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [28]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 48.0 79000.0]]


In [29]:
print(y_train)

[0 0 0 1 1 1 0 1]


In [31]:
print(y_test)

[0 1]


## Feature Scaling

In [0]:
# Scaling all features so they all take values in the same scale; ONLY apply to numerical values
# This step AFTER splitting dataset to prevent test set feature leakage (not good since test set is for FUTURE data sets)
# 2 techniques: standardization and normalization (---> normalization works for normal curve data sets)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [33]:
print(x_train)

[[0.0 0.0 1.0 -0.11575350611292926 -0.2008165165172118]
 [0.0 1.0 0.0 1.8075355185326667 1.9057620408553975]
 [1.0 0.0 0.0 0.8458910062098687 0.8524727621690928]
 [0.0 0.0 1.0 -1.8787684453713922 -1.4456129367828445]
 [0.0 1.0 0.0 0.20479466466133672 0.06516562456518865]
 [1.0 0.0 0.0 -0.5965757622743283 -0.488077228886204]
 [0.0 0.0 1.0 0.008904115854840975 -1.0625986536241883]
 [1.0 0.0 0.0 -0.27602759150006223 0.3737049082207725]]


In [34]:
print(x_test)

[[0.0 1.0 0.0 -1.3979461892099931 -0.8710915120448602]
 [1.0 0.0 0.0 1.4869873477584008 1.5227477576967412]]
